# Server
server.port=8082

# Application
spring.application.name=catalog-service

# MongoDB
spring.data.mongodb.uri=${MONGODB_URI:mongodb://localhost:27017/shopflow_catalog}
spring.data.mongodb.database=${MONGODB_DATABASE:shopflow_catalog}

# Actuator
management.endpoints.web.exposure.include=health,info

# Logging
logging.level.com.shopflow.catalog_service=DEBUG