# Server
server.port=8085

# Application
spring.application.name=payment-service

# PostgreSQL
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/shopflow_payments}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true

# Payment Mock
payment.gateway.mock=true
payment.currency.default=COP

# Actuator
management.endpoints.web.exposure.include=health,info

# Logging
logging.level.com.shopflow.payment_service=DEBUG